# Generated by Django 3.0.2 on 2020-01-28 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Manufacturer',
            new_name='manufacturer',
        ),
    ]
